import Head from 'next/head';
import Image from 'next/image';
import { useTranslation } from 'react-i18next';

import { Heading, Text, Flex, Stack } from '@chakra-ui/react';

import Container from '../components/Container';
import '../i18n/config';

export default function Home() {
    const { t } = useTranslation();
    return (
        <Container>
            <Head>
                <title>Home - BeSD UX Team</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Stack
                as='main'
                spacing={8}
                justifyContent='center'
                alignItems='flex-start'
                m='0 auto 4rem auto'
                maxWidth='1000px'
            >
                <Flex
                    flexDirection='column'
                    justifyContent='flex-start'
                    alignItems='flex-start'
                    maxWidth='1000px'
                >
                    <Heading>Home</Heading>
                    <Text>Welcome to the home page!</Text>
                </Flex>
            </Stack>
        </Container>
    );
}
