import Head from 'next/head';
import { Stack, Flex, Heading } from '@chakra-ui/react';
import Container from '../components/Container';

export default function Projects() {
    return (
        <Container>
            <Head>
                <title>Projects</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Stack
                as='main'
                spacing={8}
                justifyContent='center'
                alignItems='flex-start'
                m='0 20px 4rem 20px'
            >
                <Flex w='100%' justifyContent='center' alignItems='flex-start'>
                    <Heading as='h1'>Projects</Heading>
                </Flex>
            </Stack>
        </Container>
    );
}
