import Head from 'next/head';
import { Stack, Flex, Heading, SimpleGrid } from '@chakra-ui/react';
import { useTranslation } from 'next-i18next';

import Container from '../../components/Container';
import ProjectCard from '../../components/ProjectCard';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

export default function Projects() {
    const { t } = useTranslation('global');
    return (
        <Container>
            <Head>
                <title>Projects</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Stack
                as='main'
                spacing={8}
                justifyContent='center'
                alignItems='flex-start'
                m='0 20px 4rem 20px'
                maxWidth='1000px'
                w='100%'
            >
                <Flex w='100%' justifyContent='center' alignItems='flex-start'>
                    <Heading as='h1'>{t('pages.projects')}</Heading>
                </Flex>
                <Flex
                    gridColumnGap='1.5rem'
                    gridRowGap='4rem'
                    flexWrap='wrap'
                    justifyContent='center'
                    py={10}
                >
                    <ProjectCard
                        projectName='Project X'
                        img={{ src: '/assets/map.png', alt: 'Image of Map' }}
                        to='/about'
                    />
                    <ProjectCard
                        projectName='Project Y'
                        img={{ src: '/assets/map.png', alt: 'Image of Map' }}
                        to='/about'
                    />
                    <ProjectCard
                        projectName='Project Z'
                        img={{ src: '/assets/map.png', alt: 'Image of Map' }}
                        to='/about'
                    />
                    <ProjectCard
                        projectName='Project W'
                        img={{ src: '/assets/map.png', alt: 'Image of Map' }}
                        to='/about'
                    />
                </Flex>
            </Stack>
        </Container>
    );
}

export async function getStaticProps({ locale }) {
    return {
        props: {
            ...(await serverSideTranslations(locale, ['global'])),
        },
    };
}
