import Head from 'next/head'

export default function About() {
    return (
      <div>
        <Head>
          <title>About Us</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <h1>
            About Us
          </h1>
        </main>
      </div>
    )
}