import Head from 'next/head'

export default function Contact() {
    return (
        <div>
          <Head>
            <title>Contact Us</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main >
            <h1 >
              Contact Us
            </h1>
          </main>
        </div>
    )
}